# Generated by Django 4.1.5 on 2023-02-03 19:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import pulsifi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0014_alter_report_assigned_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That Email Address is already in use by another user.'}, max_length=254, unique=True, validators=[pulsifi.validators.HTML5EmailValidator, pulsifi.validators.FreeEmailValidator, pulsifi.validators.ConfusableEmailValidator, pulsifi.validators.PreexistingEmailTLDValidator, pulsifi.validators.ExampleEmailValidator], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.-]+\\Z', 'Enter a valid username. This value may contain only letters, digits and ./_ characters.'), pulsifi.validators.ReservedNameValidator, pulsifi.validators.ConfusableStringValidator], verbose_name='Username'),
        ),
    ]
